  
version: "3.4"
services:
  api: 
    container_name: ejemplo
    restart: always
    build: ./API
    ports: 
      - "80:5000"
    links:
      - mongodb
    volumes:
    - /proc:/proc

  mongodb:
    container_name: mimongo
    image: mongo
    ports:
      - "8080:27017"
    